xdg_open = false
xdg_open_fork = true
use_trash = true
watch_files = true

[display]
automatically_count_files = true
collapse_preview = false
column_ratio = [3, 8, 8]
scroll_offset = 6
show_borders = true
show_hidden = true
show_icons = true
tilde_in_titlebar = true
line_number_style = "absolute"

[display.sort]
method = "natural"
case_sensitive = true
directories_first = true
reverse = false

[preview]
use_preview_script = true
preview_images = true
max_preview_size = 10485760
preview_script = "~/.config/joshuto/preview_file.sh"
preview_shown_hook_script = "/home/cisco/.config/joshuto/on_preview_shown"
preview_removed_hook_script = "/home/cisco/.config/joshuto/on_preview_removed"

[tab]
home_page = "home"
